### ISSUE TITLE
Screenshot file other than PNG format

### ISSUE THREAD

**Issue by ernilambar** [WordPress/theme-check#111]
In following line we have checked only PNG file of screenshot like `screenshot.png`.
https://github.com/Otto42/theme-check/blob/master/main.php#L42

When I was reviewing a theme, there was `screenshot.jpg`. So screenshot was not displayed in the result page of TC.

**Comment by Otto42** [comment]
Relatively minor. For a long time, screenshots could only really be PNG files.

**Comment by ernilambar** [comment]
Yes, its low priority. But it would be good enhancement as core support both PNG and JPG.

**Comment by justnorris** [comment]
This is not a minor issue anymore.

Theme-check cries when jpg is used, themes are rejected because of it. Now that Retina is a popular word, we're using 1200x900 HiDPI files, which is 900kb in PNG format. That's about the size of a regular theme.

**Comment by justnorris** [comment]
Looks like everything is there already: https://github.com/WordPress/theme-check/blob/2c818f1b87cd6444968c8869a22e2955c08f5b4d/checks/screenshot.php

Weird.

**Comment by milindra** [comment]
Check my update on main.php for .jpg .png .gif image type

**Comment by milindra** [comment]
my pull request is #211

**Comment by carolinan** [comment]
The check already allows both file types, so I am closing this issue.
https://github.com/WordPress/theme-check/blob/master/checks/screenshot.php#L16
