### ISSUE TITLE
site_url() vs home_url() info check

### ISSUE THREAD

**Issue by justintadlock** [WordPress/theme-check#119]
I think it might be worth adding a quick info check for the use of `site_url()`.  I've come across a few themes that were using it when they should've been using `home_url()`.

Info check should read something like:

> Theme is using `site_url()`. `site_url()` references the URL where the WordPress files are located. Use `home_url()` if the intention is to point to the site address (home page).

**Comment by AlbertGuadan** [comment]
[site_url](https://codex.wordpress.org/Function_Reference/site_url)  ,[ home_url](https://codex.wordpress.org/Function_Reference/home_url target="_blank")
