### ISSUE TITLE
No PHP or JS errors. [Required]

### ISSUE THREAD

**Issue by grappler** [WordPress/theme-check#122]
Creating this issue after the last team meeting. https://make.wordpress.org/themes/2016/03/21/work-on-requirements-automation-update-1/

The plugins on w.org are run through a PHP checker to check for errors. Hopefully we can do something similar here. Ideas are welcome how best to do this.

**Comment by dingo-d** [comment]
Not 100% sure about this issue. If we find that this plugin generates PHP or JS errors, we'll fix those and try to get powers that be to update it 🙂
