### ISSUE TITLE
Plugin territory [Warning]

### ISSUE THREAD

**Issue by grappler** [WordPress/theme-check#129]
"The theme options should not be pseudo custom post types and save non-trivial user data. Non-design related functionality is not allowed."

Check for `user_contactmethods()` and `add_meta_box()`

**Comment by khacoder** [comment]
add_meta_box() can be legitimate I think, when used for design purposes.

**Comment by grappler** [comment]
Yes, that is why it would only be a aid for theme reviewers to check if it used for design purposes.

**Comment by carolinan** [comment]
Closing this, because a check for user_contactmethods has been added with #222
