### ISSUE TITLE
Add **INFO** check for `ABSPATH` use

### ISSUE THREAD

**Issue by chipbennett** [WordPress/theme-check#14]
We don't need to flag `ABSPATH` use as a warning or required or even recommended. But highlighting it as something to take a look at, to ensure it is used correctly (or that something else isn't implemented incorrectly) would be helpful.

Something like: "Use of `ABSPATH` detected at [ref]. Verify that it is used appropriately."

**Comment by dovy** [comment]
@chipbennett is this an appropriate use?
```php
    if ( ! defined( 'ABSPATH' ) ) {
        exit;
    }
```

I have this at the top of virtually every major class in Redux. You're going to add a whole ton of info notices adding this.  :P

**Comment by Otto42** [comment]
More to the point, do we have examples of inappropriate uses?

**Comment by pattonwebz** [comment]
With there being no examples of inappropriate use here I am going to close this issue for now - but if there are concrete examples of how authors should not have this in their files then we can reopen and make a PR with some regex to catch it :)
