### ISSUE TITLE
Check for "menu" arg in `wp_nav_menu` [Required]

### ISSUE THREAD

**Issue by grappler** [WordPress/theme-check#142]
For example. `wp_nav_menu( array('menu' => 'secondary' ) );`

**Comment by chipbennett** [comment]
Yes, please. Additionally, ensure that `'theme_location' => {location}` is included - unless doing so would be overkill?

**Comment by grappler** [comment]
Possible regex:
`/wp_nav_menu.*?array.*?(?:(menu)|\);).*?\);/gs` https://regex101.com/r/vN9zE6/1
 and `/wp_nav_menu.*?array.*?(?:(theme_location)|\);).*?\);/gs` https://regex101.com/r/rZ9lO4/1
