### ISSUE TITLE
Add a check for the <script> tag in the header.php

### ISSUE THREAD

**Issue by grappler** [WordPress/theme-check#149]
All scripts need to be enqueued. The exception is for this at the moment loading browser specific scripts in a function. We can soon remove the exception soon as `wp_script_add_data()` was introduced in WP 4.1

**Comment by Otto42** [comment]
The wp_add_inline_script was only added in WordPress 4.5. This will need to be a RECOMMENDED for a few versions before it can be a requirement.

**Comment by grappler** [comment]
We are already requiring themes to add inline script using `wp_head`. This check would only check the header.php for themes adding scripts like html5.js and similar. We could theoretically see if the tag contains `src` but themes should not be adding scripts in the header as it becomes a bit more difficult to remove. It is easier to remove with `remove_action`

**Comment by carolinan** [comment]
This is still a very common problem.

Here are some examples, but they also include styles and footer.php:

https://themes.svn.wordpress.org/photography-simple/1.2/header.php
https://themes.svn.wordpress.org/blogos/0.3/header.php
https://themes.svn.wordpress.org/montero/1.0.0/header.php
https://themes.svn.wordpress.org/midium/1.0/footer.php
https://themes.svn.wordpress.org/ilse-marie/1.0.3/footer.php
