### ISSUE TITLE
Make add_theme_support required if tag exists

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/theme-check#150]
Right now theme check shows the following error if the theme doesn't contain: `add_theme_support( "post-thumbnails" );`

> RECOMMENDED: No reference to post-thumbnails was found in the theme. If the theme has a thumbnail like functionality, it should be implemented with add_theme_support( "post-thumbnails" )in the functions.php file.

That's fine for the some themes. But if a theme contains `featured-images` tag in its style.css file, then it should be required.

Same goes for `post-formats`, `editor-style`, `custom-background`, `custom-header` and a lot of tags.

Hope it's valid idea. :)

**Comment by grappler** [comment]
Yes, we started the discussion at https://github.com/Otto42/theme-check/issues/128

**Comment by grappler** [comment]
Looking at the code, it seems like an old check to see if the theme was using a custom solution for featured images. https://github.com/Otto42/theme-check/blob/master/checks/postthumb.php

I suppose we could remove this check now as it is not likely to come up. Post Thumbnails was introduced in WP 2.9
