### ISSUE TITLE
Info message for old way of Custom Header Implementation

### ISSUE THREAD

**Issue by ernilambar** [WordPress/theme-check#152]
I have seen some constants being used in some theme. Eg, `HEADER_IMAGE_WIDTH`, `HEADER_IMAGE_HEIGHT`. It would be great if we add some `INFO` message to encourage implementing `add_theme_support( 'custom-header' )`

**Comment by ernilambar** [comment]
Following are the `define` variables which are deprecated.

* NO_HEADER_TEXT
* HEADER_IMAGE_WIDTH
* HEADER_IMAGE_HEIGHT
* HEADER_TEXTCOLOR
* HEADER_IMAGE
* BACKGROUND_COLOR
* BACKGROUND_IMAGE

@grappler What if we make it required and fail process if such define variables are used in the theme. They are deperecated since long time.

**Comment by grappler** [comment]
Yes, I would be fine with that due to this comment in core:
> // Constants are lame. Don't reference them. This is just for backwards compatibility.

**Comment by ernilambar** [comment]
Fixed in https://github.com/WordPress/theme-check/pull/162
