### ISSUE TITLE
Allow Text Domain check to work on w.org

### ISSUE THREAD

**Issue by grappler** [WordPress/theme-check#160]
The text domain was failing on w.org because of the way the Theme Check is being loaded.

[`WPORG_Themes_Upload::check_theme()`](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/theme-directory/class-wporg-themes-upload.php#L468) directly calls `checkbase.php` without loading `main.php` which defines data about the theme which is need for the text domain check.

**Comment by dingo-d** [comment]
Shouldn't this be fixed in the meta repo?

```php
/**
 * Sends a theme through Theme Check.
 *
 * @param array $files All theme files to check.
 * @return bool Whether the theme passed the checks.
 */
public function check_theme( $files ) {
        // Load the theme checking code.
        if ( ! function_exists( 'run_themechecks' ) ) {
                include_once WP_PLUGIN_DIR . '/theme-check/main.php';
                include_once WP_PLUGIN_DIR . '/theme-check/checkbase.php';
        }
        ...
```

I can open a meta ticket for this and write a patch if that will help.

**Comment by carolinan** [comment]
@dingo-d Any update?

I am not sure how to test "the text domain was failing".

I see the following theme check result added to trac tickets:
`WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs. The domains found are (removed), textdomain`

So the warning for multiple text domains works, but not the check for "wrong text domain found"?

A manual review will always be needed until themes can define multiple text domains.

**Comment by dingo-d** [comment]
I don't recall creating a meta patch for this (and from the looks of it I didn't https://meta.trac.wordpress.org/query?status=accepted&status=assigned&status=new&status=reopened&status=reviewing&reporter=dingo_d&order=priority).

Not sure I'm the best person to ping about this atm 🤷‍♂️

**Comment by dd32** [comment]
Let's fix this in theme-check by adding a new function that the Theme Uploader can call instead of `run_themechecks()`?

Something like
```
function run_automated_theme_checks( $theme_data, $themename, $files ) {
   $GLOBAL['data'] = $theme_data;
   $GLOBAL['themename'] = $themename;

  $php, $css, $other  = split $files;

  return run_themechecks( $php, $css, $other );
}
```
