### ISSUE TITLE
You are not allowed to hide the admin bar.

### ISSUE THREAD

**Issue by wordica** [WordPress/theme-check#163]
REQUIRED: You are not allowed to hide the admin bar.

I do not use in my theme any function to hide admin bar. I just check like this:

$check_a_ = get_user_meta(get_current_user_id(),'show_admin_bar_front');

if admin is on by user or not. Does this create this error?

**Comment by grappler** [comment]
I don't think the theme check is checking for `show_admin_bar_front`. Do you have the link to the themes code?

Where are you submitting the theme?

**Comment by wordica** [comment]
I can't put link but for sure I don't do nothing to hide admin bar - I only check if it's visible or not.

**Comment by wordica** [comment]
Theme-check has bug - it shows error when someone have #wpadminbar{} in CSS.

**Comment by grappler** [comment]
It is not a bug but a deliberate check to try to spot themes that are hiding the admin bar with CSS: The check has been changed from required to warning. https://github.com/Otto42/theme-check/pull/165

**Comment by flynn723** [comment]
This is still required, when I use theme checker.

**Comment by AshekurRahman** [comment]
How to solve this problem. same to me.

**Comment by wordica** [comment]
Right now I use jQuery to check if user use admin bar or not and it solve problem with theme check

**Comment by danyj** [comment]
it is also triggered with this 

`#wpadminbar .quicklinks .{... any property`

**Comment by carolinan** [comment]
It seems only one of the checks were changed to a warning, so this needs to be updated.
