### ISSUE TITLE
warrning with echoing short tags

### ISSUE THREAD

**Issue by xandros15** [WordPress/theme-check#172]
I got error `WARNING: Found PHP short tags in file` `Line 20: <a class='<?= $tab['class'] ?>'`.
I know using the normal short tags `<?` is bad practice, 'cuz colision with xml, 
but after php 5.4 `<?=` is a safer to use, and makes cleaner template script than `<?php echo`.

**Comment by grappler** [comment]
We will be updating this as we move over to using PHP code sniffer. There is pull request open to check for alterntive tags. https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/585

I am currently working on the [new theme check](https://github.com/WPTRT/WordPress-Coding-Standards) instead of fixing issues here.

You can create all pull request if you want. The check is found in `phpshort.php`

**Comment by Otto42** [comment]
Why would we allow short echo's? Those should not be used. They don't work in PHP < 5.4.

The problem with short echo is that it makes it too easy to accidentally output unsanitized data, potentially leading to XSS vulnerabilities. At least requiring the use of "echo" makes it obvious when something is being output to the page. Just doing <?= $variable ?> does not make it as obvious that the variable is being output or needs to be sanitized properly, at least not as much as <?php echo $variable ?> does.

My vote would be to not allow use of short echo in themes at all. It makes no sense to introduce potential security mistakes just to save a few keystrokes.

**Comment by xandros15** [comment]
> They don't work in PHP < 5.4.

Still don't know why wordpress supports php lower than 5.4 (even lower than 5.3)
But the worsted thing is usage PHP 4 > PHP 7
(source https://w3techs.com/technologies/details/pl-php/all/all)
> too easy to accidentally output unsanitized data, potentially leading to XSS

wat? `<?php echo esc_html($var) ?>` vs `<?= esc_html($var) ?>`... so we should use `array()` too?
Views should only print data, no manipulate on it. The most of variables in views will be echoing.

Not my project, so I will don't insist.

**Comment by Ehsan-Dalvand** [comment]
See this answer: 
http://stackoverflow.com/questions/14188397/why-are-echo-short-tags-permanently-enabled-as-of-php-5-4#answer-14188438

> Short open tags are not always enabled since PHP 5.4. The documentation talks about the short echo tags. Which is a different thing....

**Comment by carolinan** [comment]
We decided to keep the existing check with a warning for the echo short tag.
Note that this is a _warning_, so it is not required and it does not prevent a theme from being uploaded to the WordPress.org theme directory. 
Not using the echo short tag is consistent with WPCS and WordPress core.
