### ISSUE TITLE
A maximum of 3 subject tags are allowed

### ISSUE THREAD

**Issue by rinkublog** [WordPress/theme-check#177]
I think any theme should not have more than 1 tag form "photography, news, holiday, food-and-drink, entertainment, education"

A "news" theme can not be use for "food-and-drink" theme. i think theme check plugin can automate it.

As per **_discussed in meeting_**, A maximum of 3 subject tags are allowed. it will help us to avoid "invalid use of subject tags". right now many themes are using all tags.

Added pull request for the same.

https://github.com/WordPress/theme-check/pull/181

**Comment by HardeepAsrani** [comment]
It depends on the theme. A theme can be for many things, you just need to give it a layout. I've seen one theme for Music & Business, with different page templates. You can't control the creativity of an author. :)

**Comment by rinkublog** [comment]
In this case, theme need to review manually Just "Many Subject Tags" (invalid use of Subject Tags).

**Comment by grappler** [comment]
@rinkublog Please don't close the issue till the PR is merged.

**Comment by rinkublog** [comment]
@grappler ok Thanks
