### ISSUE TITLE
Required: The "<title>" tags can only contain a call to "wp_title()". Use the  "wp_title filter" to modify the output.

### ISSUE THREAD

**Issue by ghost** [WordPress/theme-check#191]
Despite using
```
if ( ! function_exists( 'theme_setup' ) ) :

// @since Themename 1.0

function theme_setup() {
   // Add theme support for document Title tag
  add_theme_support( 'title-tag' );
}

endif; // theme_setup

add_action('after_setup_theme', 'theme_setup' );
```
I get
```
<title>" tags can only contain a call to "wp_title()". Use the  "wp_title filter" to modify the output.
```
when using Themecheck with wp-cli. I have no title tag in the header.
```
This theme doesn't seem to display tags. Modify it to display tags in appropriate locations.
```
Support for all other checks are added and work.

What can I do to pass this check in WordPress 4.8 please?

I have seen and tried all the other suggestions regarding the title-tag function but none of it works, not even [https://gist.github.com/tommcfarlin/958b57e0b7c78e9ff13e](https://gist.github.com/tommcfarlin/958b57e0b7c78e9ff13e).

**Comment by monolux** [comment]
I found what it was! It was a, you will be laughing, `<title>` tag commented out in the HTML. So this means the check scans for all instances of `<title>` regardless of if it is in a comment or not.

**Comment by macthecoder** [comment]
@monolux I didn't find anything like what did you find, but still I am facing such problem.

**Comment by ThemeCSS** [comment]
Same here. I am really confused. I added **add_theme_support( 'title-tag' );** in my functions.php but still got issue.

**Comment by macthecoder** [comment]
I find out the solution already. You have to check not to only on your main header from file but also throughout the whole theme. I did it on my theme's maintenance mode index file. You are not supposed to add any  html <title> tag in anywhere throughout your theme. Check this out throughout the theme. Remove it from theme. This is the only solution of it.

**Comment by ThemeCSS** [comment]
@macthecoder I already tried this search every file I have and I did not find that <title> tag. Or does a file with title string causes this issue?

**Comment by macthecoder** [comment]
Not at all. Search throughout the project with Patience. It causes for what I said before. There is no reason but occur for this issue. It only causes if you use any html <title> tag, not for any word like title.

**Comment by ThemeCSS** [comment]
Thanks @macthecoder I re-check all my files and I found out that it was on one of my widgets. Thanks again!

**Comment by macthecoder** [comment]
Welcome.

**Comment by carolinan** [comment]
A solution here would be to add file name and line number to the output.
