### ISSUE TITLE
wp_body_open required check

### ISSUE THREAD

**Issue by justintadlock** [WordPress/theme-check#209]
WordPress themes are now required to implement the `wp_body_open()` function or hook, such like `wp_head()` and `wp_footer()`.

We need a check for either `do_action( 'wp_body_open' )` or `wp_body_open()`.

**Comment by lgedeon** [comment]
Should I just link the check to https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/ ?

**Comment by carolinan** [comment]
This has been merged, closing.
