### ISSUE TITLE
Ignore wp_deregister_script warning for non-core scripts.

### ISSUE THREAD

**Issue by h71** [WordPress/theme-check#213]
If you use `wp_deregister_script` in your theme, even for non-core scripts, theme check shows a WARNING for it.
It would be great to ignore de-registering scripts if it is not a core script. E.G, sometimes because of compatibility issues with some popular plugins, you need to de-register one or more script from the plugin if it is installed.

**Comment by joyously** [comment]
It's not an error, it's a warning, meaning that it needs to be checked manually.
It doesn't seem like themes should be deregistering plugin scripts either, but _whatever_.

**Comment by carolinan** [comment]
This would mean including a list of the core scripts and keep that list up to date when it changes.

If de-registering a script is needed for a theme that is meant to be added to the theme directory then that can be discussed with the reviewer.
