### ISSUE TITLE
Customizer sanitize callback issue

### ISSUE THREAD

**Issue by niyankhadka** [WordPress/theme-check#216]
```
if( empty( $field_stype ) ) {

                $field_stype = 'theme_mod'; 
            }
            
            if( empty( $field_capability ) ) {

                $field_capability = 'edit_theme_options';
            }
            
            if( empty( $field_transport ) ) {

                $field_transport = 'refresh';
            }
            
            $wp_customize->add_setting( $field_id, array(
                'capability'          => $field_capability,
                'type'                => $field_stype,
                'default'             => $field_default,
                'transport'           => $field_transport,
                'sanitize_callback'   => 'sanitize_text_field'
            ) );
```

This is the code i use for setting of customizer. When i use theme check, it says :

> REQUIRED: Found a Customizer setting that had an empty value passed as sanitization callback. You need to pass a function name as sanitization callback.

I have made another function and i used this code : 

```
$wp_customize->add_setting( $field_id, array(
                    'capability'          => 'edit_theme_options',
                    'sanitize_callback'   => 'sanitize_text_field',
                    'default'             => $default,
                ) );
```
It is working fine and does not show any issue. 

Can you elaborate what is the differences and why is it not still valid ? Also, can you make a clear about why we cannot add setting as arguments ?

Waiting for your response as soon as possible.

Your regards
Nirajan

**Comment by carolinan** [comment]
Hi
Are you absolutely sure this is the setting that is causing the message? Because the error message does not report any line numbers.

I did not understand what you meant with:
_Also, can you make a clear about why we cannot add setting as arguments ?_
Is that actually related to this check?

**Comment by carolinan** [comment]
The line numbers are showing for this check now, which should make it easier to identify what causes the error.
Because there has been no follow up with more information, I am closing this issue.
