### ISSUE TITLE
Add additional files to the filename check

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-check#229]
We do not allow demo content in themes, add checks for:
.wie
.dat

PHPCS files must not be in the theme. It causes issues with other PHPCS installs:
phpcs.xml.dist

Decision needed: Can these be required, or do they have to stay as warnings?

**Comment by dingo-d** [comment]
Demo files are not allowed in the themes so this should block the upload imo. So `.wie` and `.dat`.

`.xml` is tricky because of WPML config XML file, but I think that has a specific name so it could be whitelisted.

**Comment by ernilambar** [comment]
This should be REQUIRED.

**Comment by dingo-d** [comment]
Since the PR has been merged I'll close this.
