### ISSUE TITLE
Update the severity levels of some checks

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-check#235]
Some checks are shown as warnings, even though they block theme uploads to the theme directory. This is a cause of confusion for theme authors.

- [x] **Non printable characters** is currently marked as required, but the check returns true and will not stop theme uploads.  It should not stop theme uploads, since it currently blocks characters that we allow. This needs to be reduced to a warning or even info, until the check can be updated.

- [x]  **cdn**  is currently marked as required, but the check returns true and will not stop theme uploads. 
_If the check returns true because of false positives, the level needs to be reduced to a warning._

- [x]  **file operations** (malware.php), is currently a warning. It blocks theme upload, but should be required for clarity. 
**If we want to allow file_get_contents, _with manual review,_ this needs to be removed from the check and added as new check with a warning**

- [x]  **PHP short tags** is currently marked as warning. The check needs to be updated to return true.

- [x]  **wrong screenshot size,**  Is currently recommended, but needs to be changed to required because this is a common problem. The check needs to return false.

- [ ]  **Missing text domain** is currently a warning and the check returns true. This needs to be updated to required, and the check needs to return false to block theme uploads.
_The check needs to include the file name and line number._

- [ ]  **Favicon** is currently an info, but needs to be required. The check should block theme uploads, and needs to return false.

- [x]  **Blacklisted file names** is currently a warning. It correctly blocks theme upload, but should be required for clarity.

- [x]  **Eval, base64_encode etc**  is currently a warning. It correctly blocks theme upload, but should be required for clarity.

- [ ]  **Google search and advertising code**  is currently a warning. It blocks theme upload, but should be required for clarity. **Needs to be validated and tested to see if it is still relevant.**

- [x]  **wp_deregister_script** is currently a warning. _As per comments below, the check now returns true, to allow exceptions._

- [x]  **Generated themes** is currently a warning. It blocks theme upload, but should be required for clarity.

- [x]  **Line endings**  is currently a warning. It blocks theme upload, but should be required for clarity.

- [x]  **Deprecated tags in style.css** is currently a warning. It blocks theme upload, but should be required for clarity.

- [x]  **worms** is currently a warning. It blocks theme upload, but should be required for clarity.

**Comment by acosmin** [comment]
@carolinan I agree that all should be `Errors` except the `wp_deregister_script` one, which should remain a warning and not block the upload. I can see some use cases for WooCommerce or other plugins.

**Comment by aristath** [comment]
I agree with the above, my only reservations are also for the `wp_deregister_script`. There are valid cases for it...
For the CDN one we just need to make sure there are no false-positives :+1:

**Comment by carolinan** [comment]
There is also the sanitize_callback check, which currently returns false.
Here is a background to why that is problematic: https://github.com/WPTRT/WPThemeReview/issues/68#issuecomment-242865861

We can update it to return true, while we try to find a better solution (finding one may not be possible).

**Comment by dingo-d** [comment]
So we are mostly in agreement: deregister script shouldn't block, CDN should block, but we need to be careful not to block if blacklisted CDNs are in comments (for whatever reason they would be there 🤷‍♂️ )

**Comment by carolinan** [comment]
Closing this, a new issue will be opened where the severity level of each check can be followed up on.
