### ISSUE TITLE
Update deprecated functions and classes

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-check#247]
Update the deprecated check to include functions and classes deprecated in 5.3 - 5.4

https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WP/DeprecatedFunctionsSniff.php#L1349

https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/WP/DeprecatedClassesSniff.php#L60

**Comment by joyously** [comment]
I had already looked at this for Theme Check. I don't think we should include all deprecated functions (at least we don't for previous versions), but only the ones that apply to themes.

**Comment by carolinan** [comment]
OK, I agree with that. Lets close this issue for now :) And if they use a deprecated function they will still get a notification within WordPress.
