### ISSUE TITLE
Non-GPL compatible source reference in Font Awesome

### ISSUE THREAD

**Issue by mirucon** [WordPress/theme-check#259]
I've seen the non-GPL image reference detection is introduced in #239, however, it occurs a problem with Font Awesome.
In Font Awesome, there is a class named `fa-unsplash` and SVG glyph named `unsplash`. I believe that they are detected as a reference to non-GPL images, but I don't think this behavior is intentional.

I don't really have a solution to this situation though; replacing `stripos()` with `preg_match_all()` and use negative lookbehind/ahead regex is likely the simplest implementation, but it must slow down the performance.

**Comment by carolinan** [comment]
And one solution is to include the icons that the theme actually uses.

**Comment by carolinan** [comment]
I believe the intention was for this to only be a warning. I have to look at the history/ discussions to see why it is now marked as required.
