### ISSUE TITLE
Allow top-level admin menus creation

### ISSUE THREAD

**Issue by aristath** [WordPress/theme-check#260]
It was decided that themes will be allowed to add a top-level admin-menu, so we should remove the existing check and not have it block theme-uploads.

**Comment by joyously** [comment]
It was discussed, even after the "decision", yet nothing was made of the discussion, and not even waiting until another meeting (which are now a month apart) to revisit the topic. Yet this was merged anyway.
The PR doesn't even change the error message; just the exceptions. That makes it difficult to follow for future maintainers.
I personally think this should be reverted.
