### ISSUE TITLE
XML files are blanket-blocked, including some used by plugins

### ISSUE THREAD

**Issue by CryoutCreations** [WordPress/theme-check#263]
All XML files included in the theme are currently blanket blocked on upload, except WPML's `wpml-config.xml`.  
There are other plugins in the repository which use xml files from the theme for improved compatibility or integration - [Loco Translate](https://wordpress.org/plugins/loco-translate/) (a translation management plugin) being one of them. 

#262 extends the xml allowlist to include the plugin's `loco.xml` file (and supports future additions by changing the check to use an array of filenames). 

The PR also fixes the inclusion of `wpml-config.xml` in the error message (if other xml files are found) even though it is allowed.

**Comment by pattonwebz** [comment]
Hey @CryoutCreations, 

The latest version of theme check on the uploader should allow you to add your translation xml file now. If it doesn't let me know and I will check again. Thank you for opening the issue and for the PR :)
