### ISSUE TITLE
Version 20200731.1 fails without providing required items

### ISSUE THREAD

**Issue by Misplon** [WordPress/theme-check#266]
Hi everyone :)

It seems that 20200731.1 is producing a failed result without providing required items/errors. I haven't tested 20200731.1 on a theme without Recommended and Info items so I'm not sure if that's part of the problem.

To replicate the issue:

* Run Theme Check on the Twenty Twenty theme.
* Fix the style.css error by adding a `Tested up to` tag.
* Fix the `.stylelintrc.json` error by removing that file.

Expected result: Theme passes.
Observed result: `One or more errors were found for Twenty Twenty.`

![theme-check-twenty-twenty](https://user-images.githubusercontent.com/789159/89101709-ae72be80-d402-11ea-8529-223305a91c66.jpg)

Thanks

**Comment by pattonwebz** [comment]
Hey @Misplon, Thanks for reporting this so quickly. The latest version should have fixed this problem, if you are able to re-test and find it has not fixed the problem feel free to reopen this issue.

Thanks again for your report.

**Comment by Misplon** [comment]
Hi @pattonwebz. 

Super, thanks for the quick resolution, appreciate it. I've tested and the problem is resolved. 

Cheers for now.
