### ISSUE TITLE
Ignore node_modules/ and vendor/ directories

### ISSUE THREAD

**Issue by paulschreiber** [WordPress/theme-check#269]
When scanning, the plugins should omit these directories. (Scanning them is unnecessary and will cause timeouts.)

**Comment by pattonwebz** [comment]
Hey @paulschreiber, I have a PR up that is still to be fully tested that adds filters to do just this :) https://github.com/WordPress/theme-check/pull/268

**Comment by joyously** [comment]
Since the plugin is the same as used for the theme repo, it shouldn't ignore anything, or even have a filter. The developer should only test with the theme in the state it will be uploaded. So this isn't actually a problem of Theme Check. It is a problem with how authors develop. 
The development files should be separate from test and production.

**Comment by pattonwebz** [comment]
I agree this is not really a theme-check problem but I do not agree that people must test with the final set of files only. Scanners are most effective when they can be run at-will and quickly.

Developers should be able to test at any point they choose. They shouldn't need to build a 'final' version just to check things mid way through development.

It's worth noting that even if the filter is used from my PR the actual files that are important for what theme-check does (the .php and the .css files) are still included in the scan regardless of them being inside those directories. The filter only excludes files that fall into the `other` category.

**Comment by paulschreiber** [comment]
I agree with @pattonwebz. Scanning the development version lets you quickly iterate fixes.

**Comment by pattonwebz** [comment]
A filter was added that allows the parts of these directories to be skipped in local checks was added in #268
