### ISSUE TITLE
Update allowed tags list

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/theme-check#271]
The allowed tags list in the checker is a static list which does not match what the filters show on .org.

Specifically the 'block-patters' tag is missing. It has not been noticed till now because the patterns were only introduced in WP 5.5 this last week.

**Comment by joyously** [comment]
Whoever adds it, spell it right...

**Comment by pattonwebz** [comment]
@joyously I copy/pasted right from the tags page :) https://github.com/WordPress/theme-check/pull/272/commits/67742a3848386163892fae97d9d1b6afb4428c89
