### ISSUE TITLE
Mention only major version for Requires PHP and Tested up to

### ISSUE THREAD

**Issue by kafleg** [WordPress/theme-check#341]
In theme style.css file, it should be mentioned
```
Requires PHP: 5.2
Tested up to: 5.7
```
but most of the theme author mentioned minor version as well. For example,
```
Requires PHP: 5.2.3
Tested up to: 5.7.2
```

As @Otto42 said that it is only recommended to mention the major version. His [comment](https://themes.trac.wordpress.org/ticket/84095#comment:2) in a ticket,

> While we are not using the "Tested up to" parameter yet for themes, for the case of plugins, we generally recommend leaving it at the major version number only. That is, WordPress is at 5.4.1, but Tested up to can be at 5.4 without any issues.
> 
> In the plugin directory, we automatically assume that minor versions are compatible if you specify it in this manner, and will show the latest version without you needing to update to every minor version.
> 
> When this gets implemented for themes, I expect that we will use the same basic formula. So "Tested up to: 5.4" is fine. No need to specify 5.4.0 or 5.4.1 and so on. Just for the future.
>

**Comment by TeBenachi** [comment]
#373

**Comment by carolinan** [comment]
I am closing the issue since this has been completed. 🎉
