### ISSUE TITLE
Latest release throwing a 255 error in CI builds

### ISSUE THREAD

**Issue by eherman-godaddy** [WordPress/theme-check#357]
Hi there,

We're using theme-check in our CI/CD pipeline to ensure our theme passes the checks on each release. However, in the latest release we're now getting a failing build with a `Exited with code exit status 255`.

We're running theme check through the WP CLI command `wp themecheck --theme=go --no-interactive`. Any ideas what might be causing this? Is it possibly the run is exhasting the memory? I'm also getting the similar results on my local machine.

![image](https://user-images.githubusercontent.com/85256006/123869160-a36c2b00-d8fe-11eb-89fa-ca47ca8352cd.png)

Here are the two builds, one passing 14 days ago, another failing run today, same branch.

**Passing:**
https://app.circleci.com/pipelines/github/godaddy-wordpress/go/2328/workflows/aaeeaeac-2929-4a6e-9a1d-aa5e33375674/jobs/11440

**Failing:**
https://app.circleci.com/pipelines/github/godaddy-wordpress/go/2328/workflows/f1ab1d58-f952-467d-a4fb-b5d1d4747823/jobs/11474

**Comment by eherman-godaddy** [comment]
Closing, as this is more likely related to https://github.com/anhskohbo/wp-cli-themecheck

**Comment by carolinan** [comment]
There was a large update to the plugin two weeks ago, if it helps the changelog is here
https://github.com/WordPress/theme-check/pull/348/files
