### ISSUE TITLE
Notice message with v.20210617

### ISSUE THREAD

**Issue by TeBenachi** [WordPress/theme-check#358]
Hi.  I noticed there is an error message with  v 20210617. 
I tried with 2 different fresh installs using Local, WordPress v. 5.7.2 on PHP 7.4.1. 

Error message goes "Notice: Undefined offset: 1 in /plugins/theme-check/main.php on line 99"

Twenty Nineteen, Twenty Twenty, and Twenty Twenty-One have the same notice.  

![screenshot](https://user-images.githubusercontent.com/30734209/124003119-90ac3180-d9a4-11eb-8f20-081e05be6bd1.jpg)

**Comment by TeBenachi** [comment]
Please discard this. I tried again with different server and It seems to be working.

**Comment by carolinan** [comment]
It is valid, so I will reopen it. See https://github.com/WordPress/theme-check/pull/354#issuecomment-872007456
I did not see this issue before commenting.

**Comment by TeBenachi** [comment]
The issue seems to be solved after creating a PR #364 with the new revision number. 
Thanks!
