### ISSUE TITLE
Block uploads when there is logo set in default

### ISSUE THREAD

**Issue by kafleg** [WordPress/theme-check#368]
While reviewing themes, some themes use a custom logo(Icons or Text) instead of showing Site Title or Tagline in default. It will make that the logo of the author will be shown on the user's sites. 

For example, see the code in this ticket.  https://themes.svn.wordpress.org/ctpress/1.0.8/template-parts/header/logo-center.php

This theme has a logo that is displayed in default instead of the site title and tagline.

**Comment by carolinan** [comment]
What are the negative impacts of allowing a logo?
Why does it need to block upload?


The downside to themes adding a logo is that the users needs to change it if they want their own.
-Users would need to add their own logo even if the logo option was empty.

Another downside is that the logo is visible in the theme preview. Does this have any impact at all?
Does it matter if this is the theme authors logo?

The only real down side as I can see it, is if the logo can't be replaced. How do we test that? 
Do we want to spend time on test that can:

- Log in
- go to the customizer,
- open the logo setting
- upload or select a new logo
- save
- confirm that the logo is updated

**Comment by carolinan** [comment]
Also, with the custom logo being a block, theme authors can use the block to add an image to illustrate to the user where the logo is positioned.

**Comment by kafleg** [comment]
If the author uses a similar popular brand logo when the user activates the theme and it will be displayed on the user's site. 
If that doesn't fall under any trademark issues or any other issues, that is fine with me. 

And yes, logo should be replaceable.

**Comment by kafleg** [comment]
I haven't seen this issue for a long time. So, I am marking this issue as closed now. We can reopen later if needed.
