### ISSUE TITLE
PHP Notice in i18n check

### ISSUE THREAD

**Issue by dd32** [WordPress/theme-check#374]
```
E_NOTICE: Uninitialized string offset: 884 in wp-content/plugins/theme-check/checks/class-i18n-check.php:47
```

I don't have any more information, other than that this particular theme (`oldschool.zip`) being run through the checks triggered that notice for offsets 1 through 1200..

**Comment by carolinan** [comment]
I have not been able to reproduce this.

**Comment by dd32** [comment]
Based on that, it sounds like maybe it's a parse error? something like `_e( 'string', 'textdomain' ));`?

**Comment by kafleg** [comment]
I checked by making such errors locally, I am not able to get any notice or errors. To test it, do we need to try uploading in trac? If yes, that might not be the proper way of testing things?

**Comment by dd32** [comment]
It wasn't a trac-specific issue, and I wasn't sure what the exact issue was since I've still not seen code.

It looks like it's triggered with this invalid PHP though, I had guessed an extra trailing `)` but it's an extra leading `(`
````
$var = __(( "String" );
```

Example: https://3v4l.org/jDPIg#v8.0.9

I'm guessing that simply validating that `$i <= strlen( $string )` in the `while()` might do the job to avoid this happening again, it would've failed PHP Lint checks later when it was attempted to be commited to svn..  but they never got that far, as it was simply timing out by generating so many warnings.
