### ISSUE TITLE
Upload Error 

### ISSUE THREAD

**Issue by kafleg** [WordPress/theme-check#381]
It shows an upload error but the theme is uploaded and the message is not actually an error. 

![image](https://user-images.githubusercontent.com/13062231/128895337-2e89bed4-14da-425e-a0a9-68af5f24e999.png)

**Comment by carolinan** [comment]
@StevenDufresne This might be related to https://github.com/WordPress/wordpress.org/pull/36

**Comment by StevenDufresne** [comment]
Should be addressed in https://meta.trac.wordpress.org/changeset/11172.

Reopen on wordpress.org otherwise!

**Comment by carolinan** [comment]
@kafleg is this issue solved?

**Comment by kafleg** [comment]
I haven't seen it now.  But, to verify I need to upload the theme again.

**Comment by kafleg** [comment]
I will create an issue again if I see a similar issue in the future. I haven't seen this error for a long time.
