### ISSUE TITLE
Check if the theme has a copyright notice

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-check#382]
GPL **requires** that there is a copyright notice for the theme.
The easiest description of this is in the howto: https://www.gnu.org/licenses/gpl-howto.html

Example formats from gnu: `Copyright 1998, 1999 Terry Jones`, `Copyright 1998-2021 Terry Jones`.

First, we know that themes do not use consistent formatting or placement for the copyright notice.
Secondly, third party assets includes a copyright notice (as they should) that the check needs to ignore.
And third, theme authors often copyrights their work to:
- WordPress.org, WordPress, WordPress.org team (they copy default themes)
- Automattic (they copy underscores)
- Fred 🤷‍♀️

because Fred is used in the example:
https://make.wordpress.org/themes/2014/07/08/proper-copyrightlicense-attribution-for-themes/

Finally, the copyright notice **should not** be included if the theme license is public domain, which happens but is rare.

I think the best option is to add a check that requires the word "Copyright" to be inside either style.css or readme.txt,
but not check for further formatting.

**Comment by kafleg** [comment]
That word might be the best option to check on those files.  Some themes can have a © symbol too. We can add an INFO about this.

**Comment by carolinan** [comment]
The current check is very limited, but better than none, and a reminder to theme authors.
