### ISSUE TITLE
Screenshot dimensions

### ISSUE THREAD

**Issue by kafleg** [WordPress/theme-check#387]
Theme having invalid screenshot size doesn't restrict uploads or not showing any information in Theme Check Results: section in trac. Ticket, https://themes.trac.wordpress.org/ticket/104212

**REQUIRED Screenshot dimensions are wrong! The ratio of width to height should be 4:3.**

This is the message showing using the theme check plugin locally. 

Also, there is information on the RECOMMENDED section,
**RECOMMENDED Screenshot size should be 1200x900, to account for HiDPI displays. Any 4:3 image size is acceptable, but 1200x900 is preferred.**

**Comment by TeBenachi** [comment]
When a screenshot is larger than 1200x900, the theme check prompts two alerts. 
Consolidating into one alert may be less confusing to the authors. 

<img width="668" alt="Screen Shot 2021-08-18 at 4 58 46 AM" src="https://user-images.githubusercontent.com/30734209/129870488-732c9389-9006-40b0-947f-238a0c072e7c.png">

**Comment by carolinan** [comment]
Ratio and size are two different problems, not one.

**Comment by kafleg** [comment]
Related to this, https://github.com/WordPress/theme-check/pull/401 

I am closing this issue.
