### ISSUE TITLE
FSE theme check- allow for new folder names

### ISSUE THREAD

**Issue by carolinan** [WordPress/theme-check#404]
See the upcoming folder name changes for block themes planned for 5.9:
https://github.com/WordPress/gutenberg/pull/36647

```
Updates the block themes to use templates and parts instead of block-templates and block-template-parts.
It also keeps backward compatibility, that said a theme can not have "templates" and "block-template-parts"
or "block-templates" and "parts".
```

**Comment by kafleg** [comment]
Fixed and merged. [pull/406 ](https://github.com/WordPress/theme-check/pull/406)

Making this issue and closed.
