### ISSUE TITLE
Polylang function

### ISSUE THREAD

**Issue by satrya** [WordPress/theme-check#86]
Hi @Otto42 
I just added a [Polylang](https://wordpress.org/plugins/polylang/) integration to my theme, but when I tested my theme with Theme Check, it display a translation info message because Polylang function  `pll__` contain `__`. Do you think you can add something like a function check to remove the info message if we integrate Polylang to our theme?

Thank you,
Satrya

![screenshot 2015-09-04 13 18 47](https://cloud.githubusercontent.com/assets/891643/9677559/a78c9182-5305-11e5-9a12-64b6c8f90c34.png)

**Comment by Otto42** [comment]
This will likely be fixed when I move this particular check from i18n.php to the textdomain.php, which has a more robust parser system and can tell function names without regular expressions.

**Comment by Otto42** [comment]
This one is a bit hard to implement with the current code, so I won't get a fix out before the 4.4 release, but I'm reworking the textdomain code to try to eliminate this and improve it as well.

**Comment by carolinan** [comment]
I have confirmed that Polylang still uses `pll__` but since this is a recommendation,  not listed as a requirement, I vote for this issue to be closed.
